language: python
python:
      - "3.6"
before_install:
    - sudo apt-get install python-os
    - sudo apt-get install python-sys
install:
      - pip install -r requirements.txt
script:
      - pytest -v
      - pytest -v --cov --pep8
os:
      - linux
      - osx